# Configure Magnum build
set(WITH_GLFWAPPLICATION ON CACHE BOOL "" FORCE)
set(WITH_ANYIMAGEIMPORTER ON CACHE BOOL "" FORCE)
set(WITH_STBIMAGEIMPORTER ON CACHE BOOL "" FORCE)
set(WITH_MESHTOOLS ON CACHE BOOL "" FORCE)
set(WITH_PRIMITIVES ON CACHE BOOL "" FORCE)
set(WITH_SHADERS ON CACHE BOOL "" FORCE)
set(BUILD_PLUGINS_STATIC ON CACHE BOOL "" FORCE)

# Add Magnum directories
foreach(PROJECT corrade;magnum;magnum-plugins)
	add_subdirectory(external/${PROJECT} EXCLUDE_FROM_ALL)
endforeach()

# Remove unwanted hierarchy in the build directory introduced by Magnum
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
